### ISSUE TITLE
wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone

### ISSUE THREAD

**Issue by DocHifi** [atareao/my-weather-indicator#107]
When I start the program only an empty Icon in panel appears.
Starting in terminal, tell me:
`wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone `
Testing under Ubuntu Mate 20.04 and 22.04.
Some days ago it was working fine.
Version : my-weather-indicator 0.10.1-0extras23.04.00

**Comment by DocHifi** [comment]
Update:
Trying in Terminal: 
`/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator | grep -i error`
Get this:
```
023-04-15 11:16:56,580 - geocodeapi - ERROR - Error calculating rawOffset: ''
2023-04-15 11:16:56,580 - geocodeapi - ERROR - ''
Error. HTTP Error code: 400. Invalid timezone
2023-04-15 11:16:56,687 - wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone
2023-04-15 11:16:56,689 - geocodeapi - ERROR - Error calculating rawOffset: ''
2023-04-15 11:16:56,689 - geocodeapi - ERROR - ''
Error. HTTP Error code: 400. Invalid timezone
2023-04-15 11:16:56,781 - wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone
^CTraceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 918, in main
    Gtk.main()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1632, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)

```

**Comment by atareao** [comment]
Please @DocHifi run and paste here,

/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator | grep -i timezone

Or without `grep`

Thanks

**Comment by DocHifi** [comment]
`/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator | grep -i timezone`

```
2023-04-16 09:46:30,907 - geocodeapi - INFO - Timezone: 
https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current_weather=true&timezone=&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
2023-04-16 09:46:30,929 - wopenmeteoapi - INFO - https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current_weather=true&timezone=&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
Invalid timezone
Error. HTTP Error code: 400. Invalid timezone
2023-04-16 09:46:31,020 - wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone
2023-04-16 09:46:31,022 - geocodeapi - INFO - Timezone: 
https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current_weather=true&timezone=&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
2023-04-16 09:46:31,031 - wopenmeteoapi - INFO - https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current_weather=true&timezone=&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
Invalid timezone
Error. HTTP Error code: 400. Invalid timezone
2023-04-16 09:46:31,107 - wopenmeteoapi - ERROR - Error. HTTP Error code: 400. Invalid timezone

```

**Comment by atareao** [comment]
Fixed on  my-weather-indicator - 0.10.2-0extras23.04.00

**Comment by DocHifi** [comment]
Update to the new version ton´t fix it, so it is not solved.
Sorry.
