### ISSUE TITLE
Weather report shows N/A 

### ISSUE THREAD

**Issue by vaasanthk** [atareao/my-weather-indicator#99]
I have attached the screen-shot please let me know what is the issue. I changed the weather station to yahoo but still the same. I uninstalled it and reinstalled it's the same.
![Screenshot from 2023-04-10 17-45-52](https://user-images.githubusercontent.com/41782835/230900326-ca9b979e-ac5b-4b7c-acb8-b4c834d82c15.png)

**Comment by atlas909** [comment]
same problem and my second city is not working

**Comment by gimplyworxs** [comment]
There was an update of the app via PPA. Did you do that?
It's necessary because as far as I understand the weather service used is no longer free, so another one has to be used. 
Then in your configuration, choose a skin that does not display pressure.

If you need pressure, you have to edit the file
/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/weatherwidget.py
go to line 490 there and change the line from
text = text.replace('$PRESSURE$', self.weather_data['current_conditions']['pressure'])
to
text = text.replace('$PRESSURE$', str(self.weather_data['current_conditions']['pressure']))

You need to be admin for that.
Worked for me on two machines.

**Comment by GmorkK** [comment]
Hello, I have the same problem. 

How to solve it?

**Comment by gimplyworxs** [comment]
Read how I solved it in post#3 of this issue:
 https://github.com/atareao/my-weather-indicator/issues/99#issuecomment-1502828082

**Comment by dedepapa1** [comment]
Hello, I have the same problem, uninstalled and reinstalled but now impossible to launch the app when selecting the icon. 
What can I do?
Thanks

**Comment by atareao** [comment]
Fixed in my-weather-indicator - 0.10.1-0extras23.04.00

**Comment by dedepapa1** [comment]
I still have a problem. When I type in a terminal "my-weather-indicator" the app doesn't open and the reply is "command not found".
I'm on Ubuntu 22.04.2.

**Comment by gimplyworxs** [comment]
You have to start like this:
/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator

**Comment by dedepapa1** [comment]
Thanks for your reply. the reply in a terminal is below.
dede@dede-Inspiron-5570:~$  /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
Namespace GeocodeGlib not available
Repository version required not present

**Comment by gimplyworxs** [comment]
Happened to me as well..
install gir1.2-geocodeglib-1.0 :
sudo apt install gir1.2-geocodeglib-1.0

**Comment by dedepapa1** [comment]
I did have access to setting at first but only once. Now I have that reply when typing your command  /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator.

`dede@dede-Inspiron-5570:~$  /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
2023-04-14 11:56:08,568 - myweatherindicator - INFO - 
#####################################################
System: Linux
Machine: x86_64
Node: dede-Inspiron-5570
Release: 5.19.0-38-generic
Version: #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
App: My-Weather-Indicator
App version: 0.10.0-0extras23.04.00
#####################################################

2023-04-14 11:56:08,568 - myweatherindicator - INFO - My-Weather-Indicator version: 0.10.0-0extras23.04.00
2023-04-14 11:56:08,568 - myweatherindicator - INFO - #####################################################

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.573: Theme parsing error: gtk.css:27:35: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.573: Theme parsing error: gtk.css:40:48: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.573: Theme parsing error: gtk.css:48:46: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:59:58: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:66:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:70:46: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:77:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:81:58: Junk at end of value for background-color

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:123:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:124:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:156:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:157:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:177:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(my-weather-indicator:5898): Gtk-WARNING **: 11:56:08.574: Theme parsing error: gtk.css:199:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
2023-04-14 11:56:08,638 - myweatherindicator - INFO - ***** refreshing weather *****
2023-04-14 11:56:08,638 - check_connection - INFO - OK. Internet connection. HTTPConnection: www.google.com
2023-04-14 11:56:08,638 - myweatherindicator - INFO - --- Updating data in location 0 ---
2023-04-14 11:56:08,638 - myweatherindicator - INFO - ****** Updating weather
2023-04-14 11:56:08,638 - geocodeapi - INFO - ****** Calculating rawOffset
2023-04-14 11:56:08,638 - geocodeapi - INFO - Timezone: Europe/Paris
2023-04-14 11:56:08,639 - geocodeapi - DEBUG - Timezone: Europe/Paris
2023-04-14 11:56:08,639 - geocodeapi - DEBUG - Time in zone: 2023-04-14 11:56:08.639269+02:00
2023-04-14 11:56:08,639 - geocodeapi - DEBUG - Delta: 2:00:00
2023-04-14 11:56:08,639 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,639 - weatherservice - DEBUG - 2023-04-14 11:56:08.639673
2023-04-14 11:56:08,639 - moon - INFO - __init__
2023-04-14 11:56:08,639 - moon - DEBUG - 2023-04-14 11:56:08.639673
2023-04-14 11:56:08,639 - moon - INFO - position
2023-04-14 11:56:08,639 - moon - DEBUG - Dif: 8138 days, 11:56:08.639673
2023-04-14 11:56:08,639 - moon - DEBUG - Days: 8138.497314814814814814814815
2023-04-14 11:56:08,639 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,639 - weatherservice - DEBUG - 2023-04-14 11:56:08.639931
2023-04-14 11:56:08,639 - moon - INFO - __init__
2023-04-14 11:56:08,640 - moon - DEBUG - 2023-04-14 11:56:08.639931
2023-04-14 11:56:08,640 - moon - INFO - position
2023-04-14 11:56:08,640 - moon - DEBUG - Dif: 8138 days, 11:56:08.639931
2023-04-14 11:56:08,640 - moon - DEBUG - Days: 8138.497314814814814814814815
2023-04-14 11:56:08,640 - weatherservice - INFO - === 1 ===
2023-04-14 11:56:08,640 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,640 - weatherservice - DEBUG - 2023-04-14 11:56:08.640273
2023-04-14 11:56:08,640 - moon - INFO - __init__
2023-04-14 11:56:08,640 - moon - DEBUG - 2023-04-14 11:56:08.640273
2023-04-14 11:56:08,640 - moon - INFO - position
2023-04-14 11:56:08,640 - moon - DEBUG - Dif: 8138 days, 11:56:08.640273
2023-04-14 11:56:08,640 - moon - DEBUG - Days: 8138.497314814814814814814815
2023-04-14 11:56:08,640 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,640 - weatherservice - DEBUG - 2023-04-14 11:56:08.640273
2023-04-14 11:56:08,640 - moon - INFO - __init__
2023-04-14 11:56:08,640 - moon - DEBUG - 2023-04-14 11:56:08.640273
2023-04-14 11:56:08,640 - moon - INFO - position
2023-04-14 11:56:08,640 - moon - DEBUG - Dif: 8138 days, 11:56:08.640273
2023-04-14 11:56:08,641 - moon - DEBUG - Days: 8138.497314814814814814814815
2023-04-14 11:56:08,641 - weatherservice - INFO - === 2 ===
2023-04-14 11:56:08,641 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,641 - weatherservice - DEBUG - 2023-04-15 11:56:08.640273
2023-04-14 11:56:08,641 - moon - INFO - __init__
2023-04-14 11:56:08,641 - moon - DEBUG - 2023-04-15 11:56:08.640273
2023-04-14 11:56:08,641 - moon - INFO - position
2023-04-14 11:56:08,641 - moon - DEBUG - Dif: 8139 days, 11:56:08.640273
2023-04-14 11:56:08,641 - moon - DEBUG - Days: 8139.497314814814814814814815
2023-04-14 11:56:08,641 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,641 - weatherservice - DEBUG - 2023-04-15 11:56:08.640273
2023-04-14 11:56:08,641 - moon - INFO - __init__
2023-04-14 11:56:08,641 - moon - DEBUG - 2023-04-15 11:56:08.640273
2023-04-14 11:56:08,641 - moon - INFO - position
2023-04-14 11:56:08,641 - moon - DEBUG - Dif: 8139 days, 11:56:08.640273
2023-04-14 11:56:08,641 - moon - DEBUG - Days: 8139.497314814814814814814815
2023-04-14 11:56:08,641 - weatherservice - INFO - === 3 ===
2023-04-14 11:56:08,641 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,641 - weatherservice - DEBUG - 2023-04-16 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - __init__
2023-04-14 11:56:08,642 - moon - DEBUG - 2023-04-16 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - position
2023-04-14 11:56:08,642 - moon - DEBUG - Dif: 8140 days, 11:56:08.640273
2023-04-14 11:56:08,642 - moon - DEBUG - Days: 8140.497314814814814814814815
2023-04-14 11:56:08,642 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,642 - weatherservice - DEBUG - 2023-04-16 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - __init__
2023-04-14 11:56:08,642 - moon - DEBUG - 2023-04-16 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - position
2023-04-14 11:56:08,642 - moon - DEBUG - Dif: 8140 days, 11:56:08.640273
2023-04-14 11:56:08,642 - moon - DEBUG - Days: 8140.497314814814814814814815
2023-04-14 11:56:08,642 - weatherservice - INFO - === 4 ===
2023-04-14 11:56:08,642 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,642 - weatherservice - DEBUG - 2023-04-17 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - __init__
2023-04-14 11:56:08,642 - moon - DEBUG - 2023-04-17 11:56:08.640273
2023-04-14 11:56:08,642 - moon - INFO - position
2023-04-14 11:56:08,642 - moon - DEBUG - Dif: 8141 days, 11:56:08.640273
2023-04-14 11:56:08,642 - moon - DEBUG - Days: 8141.497314814814814814814815
2023-04-14 11:56:08,642 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,642 - weatherservice - DEBUG - 2023-04-17 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - __init__
2023-04-14 11:56:08,643 - moon - DEBUG - 2023-04-17 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - position
2023-04-14 11:56:08,643 - moon - DEBUG - Dif: 8141 days, 11:56:08.640273
2023-04-14 11:56:08,643 - moon - DEBUG - Days: 8141.497314814814814814814815
2023-04-14 11:56:08,643 - weatherservice - INFO - === 5 ===
2023-04-14 11:56:08,643 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,643 - weatherservice - DEBUG - 2023-04-18 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - __init__
2023-04-14 11:56:08,643 - moon - DEBUG - 2023-04-18 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - position
2023-04-14 11:56:08,643 - moon - DEBUG - Dif: 8142 days, 11:56:08.640273
2023-04-14 11:56:08,643 - moon - DEBUG - Days: 8142.497314814814814814814815
2023-04-14 11:56:08,643 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,643 - weatherservice - DEBUG - 2023-04-18 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - __init__
2023-04-14 11:56:08,643 - moon - DEBUG - 2023-04-18 11:56:08.640273
2023-04-14 11:56:08,643 - moon - INFO - position
2023-04-14 11:56:08,643 - moon - DEBUG - Dif: 8142 days, 11:56:08.640273
2023-04-14 11:56:08,643 - moon - DEBUG - Days: 8142.497314814814814814814815
2023-04-14 11:56:08,644 - weatherservice - INFO - === 6 ===
2023-04-14 11:56:08,644 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,644 - weatherservice - DEBUG - 2023-04-19 11:56:08.640273
2023-04-14 11:56:08,644 - moon - INFO - __init__
2023-04-14 11:56:08,644 - moon - DEBUG - 2023-04-19 11:56:08.640273
2023-04-14 11:56:08,644 - moon - INFO - position
2023-04-14 11:56:08,644 - moon - DEBUG - Dif: 8143 days, 11:56:08.640273
2023-04-14 11:56:08,644 - moon - DEBUG - Days: 8143.497314814814814814814815
2023-04-14 11:56:08,644 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,644 - weatherservice - DEBUG - 2023-04-19 11:56:08.640273
2023-04-14 11:56:08,644 - moon - INFO - __init__
2023-04-14 11:56:08,644 - moon - DEBUG - 2023-04-19 11:56:08.640273
2023-04-14 11:56:08,644 - moon - INFO - position
2023-04-14 11:56:08,644 - moon - DEBUG - Dif: 8143 days, 11:56:08.640273
2023-04-14 11:56:08,644 - moon - DEBUG - Days: 8143.497314814814814814814815
2023-04-14 11:56:08,644 - weatherservice - INFO - === 7 ===
2023-04-14 11:56:08,644 - weatherservice - INFO - get_moon_icon
2023-04-14 11:56:08,644 - weatherservice - DEBUG - 2023-04-20 11:56:08.640273
2023-04-14 11:56:08,644 - moon - INFO - __init__
2023-04-14 11:56:08,644 - moon - DEBUG - 2023-04-20 11:56:08.640273
2023-04-14 11:56:08,645 - moon - INFO - position
2023-04-14 11:56:08,645 - moon - DEBUG - Dif: 8144 days, 11:56:08.640273
2023-04-14 11:56:08,645 - moon - DEBUG - Days: 8144.497314814814814814814815
2023-04-14 11:56:08,645 - weatherservice - INFO - get_moon_phase
2023-04-14 11:56:08,645 - weatherservice - DEBUG - 2023-04-20 11:56:08.640273
2023-04-14 11:56:08,645 - moon - INFO - __init__
2023-04-14 11:56:08,645 - moon - DEBUG - 2023-04-20 11:56:08.640273
2023-04-14 11:56:08,645 - moon - INFO - position
2023-04-14 11:56:08,645 - moon - DEBUG - Dif: 8144 days, 11:56:08.640273
2023-04-14 11:56:08,645 - moon - DEBUG - Days: 8144.497314814814814814814815
https://api.open-meteo.com/v1/forecast?latitude=47.4704&longitude=-0.5463&current_weather=true&timezone=Europe/Paris&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
2023-04-14 11:56:08,645 - wopenmeteoapi - INFO - https://api.open-meteo.com/v1/forecast?latitude=47.4704&longitude=-0.5463&current_weather=true&timezone=Europe/Paris&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean,weathercode,sunrise,sunset,windspeed_10m_max,winddirection_10m_dominant,shortwave_radiation_sum,uv_index_max,uv_index_clear_sky_max&hourly=relativehumidity_2m,apparent_temperature,pressure_msl,dewpoint_2m,cloudcover,visibility,uv_index
200
2023-04-14 11:56:08,850 - myweatherindicator - INFO - ****** Updated weather
2023-04-14 11:56:08,850 - myweatherindicator - INFO - None
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 917, in main
    MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 139, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 339, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 154, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 672, in update_menu
    self.widgets[index].set_weather(weather)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/weatherwidget.py", line 157, in set_weather
    self.parse_data()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/weatherwidget.py", line 490, in parse_data
    text = text.replace('$PRESSURE$', self.weather_data['current_conditions']['pressure'])
TypeError: replace() argument 2 must be str, not float`

**Comment by GmorkK** [comment]
Fixed. 

I removed, then re-installed my weather indicator and now it works.
Thank You

**Comment by dedepapa1** [comment]
I uninstalled, deleted directory ~/.config/my-weather-indicator and  reinstalled, it works now.
Thanks a lot.
